spring:
  application:
    name: application-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8082
  servlet:
    context-path: /app

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

info:
  app:
    name: Application
    description: Transaction Account Application
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
